services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "Varma@10111"
      MYSQL_DATABASE: "cricket_info"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pVarma@10111"]
      timeout: 20s
      retries: 10
      interval: 5s

  backend:
    image: micronaut-backend
    build:
      context: "./micronaut-data-servlet"
      dockerfile: Dockerfile 
    container_name: micronaut-app
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DATASOURCES_DEFAULT_URL: jdbc:mysql://mysql:3306/cricket_info
      DATASOURCES_DEFAULT_USERNAME: root
      DATASOURCES_DEFAULT_PASSWORD: "Varma@10111"
    ports:
      - "8080:8080"

  frontend:
    image: react-frontend
    build:
      context: "./cricket-ui"
      dockerfile: Dockerfile
    container_name: react-frontend-app
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  mysql_data: 